package cs.trade.scheduler.core.frontend.theme

// "Graphite" — an industrial / engineering palette: cool-grey base, white elevated panels,
// one dominant cobalt accent, crisp hairline outlines. Deliberately NOT a stock Material
// baseline (lavender) nor a candy multi-hue scheme — dominant colour + sharp accent reads as
// a precise, expensive tool. State hues (teal / amber) are desaturated so cobalt stays the lead.
//
// These raw hex values are written into CSS custom properties ONCE by [SchedulerGlobalStyles];
// every component reads them through [SchedulerTheme] as `var(--sch-*)`. That indirection is
// what makes the dark-mode toggle a single attribute flip on <html> instead of a React
// re-render of the whole tree.

/** One complete set of colour-role values. Two instances exist: [LightPalette], [DarkPalette]. */
internal class SchedulerPalette(
    val primary: String,
    val onPrimary: String,
    val primaryContainer: String,
    val onPrimaryContainer: String,
    val secondary: String,
    val onSecondary: String,
    val secondaryContainer: String,
    val onSecondaryContainer: String,
    val tertiary: String,
    val onTertiary: String,
    val tertiaryContainer: String,
    val onTertiaryContainer: String,
    val error: String,
    val onError: String,
    val errorContainer: String,
    val onErrorContainer: String,
    val background: String,
    val onBackground: String,
    val surface: String,
    val onSurface: String,
    val surfaceVariant: String,
    val onSurfaceVariant: String,
    val surfaceContainerLowest: String,
    val surfaceContainerLow: String,
    val surfaceContainer: String,
    val surfaceContainerHigh: String,
    val surfaceContainerHighest: String,
    val outline: String,
    val outlineVariant: String,
    val inverseSurface: String,
    val inverseOnSurface: String,
    val inversePrimary: String,
    // Semantic roles Material has no slot for — success / warning / info. Job-state chips, the
    // connection badge and queue-health badges need a green/amber/blue that ADAPTS to light vs
    // dark instead of hardcoding light-only hex (which washes out on a dark surface).
    val success: String,
    val onSuccess: String,
    val successContainer: String,
    val onSuccessContainer: String,
    val warning: String,
    val onWarning: String,
    val warningContainer: String,
    val onWarningContainer: String,
    val info: String,
    val onInfo: String,
    val infoContainer: String,
    val onInfoContainer: String,
    /** Drop shadow for elevated panels — heavier in dark mode where borders alone read flat. */
    val shadow: String,
)

internal val LightPalette = SchedulerPalette(
    primary = "#2348E0",                    // cobalt
    onPrimary = "#FFFFFF",
    primaryContainer = "#DBE2FF",
    onPrimaryContainer = "#001550",
    secondary = "#2F6F5E",                  // muted teal — PROCESSING
    onSecondary = "#FFFFFF",
    secondaryContainer = "#CDE9DF",
    onSecondaryContainer = "#07271E",
    tertiary = "#8A5A12",                   // bronze/amber — SCHEDULED
    onTertiary = "#FFFFFF",
    tertiaryContainer = "#F5E2C4",
    onTertiaryContainer = "#2A1A00",
    error = "#C8102E",
    onError = "#FFFFFF",
    errorContainer = "#FFD9DA",
    onErrorContainer = "#40000A",
    background = "#F1F3F5",                 // cool grey canvas
    onBackground = "#1A1C20",               // graphite ink
    surface = "#FFFFFF",                    // white elevated panels pop on the grey
    onSurface = "#1A1C20",
    surfaceVariant = "#E4E7EB",
    onSurfaceVariant = "#565B62",
    surfaceContainerLowest = "#FFFFFF",
    surfaceContainerLow = "#F7F8FA",
    surfaceContainer = "#EEF0F3",
    surfaceContainerHigh = "#E8EBEE",
    surfaceContainerHighest = "#E2E5E9",
    outline = "#B9BEC5",                    // hairline borders
    outlineVariant = "#D6DADF",
    inverseSurface = "#2A2D32",
    inverseOnSurface = "#F0F1F4",
    inversePrimary = "#B4C4FF",
    success = "#0E9F6E",
    onSuccess = "#FFFFFF",
    successContainer = "#CFF5E7",
    onSuccessContainer = "#00382A",
    warning = "#B45309",
    onWarning = "#FFFFFF",
    warningContainer = "#FFE0B8",
    onWarningContainer = "#2E1500",
    info = "#2348E0",
    onInfo = "#FFFFFF",
    infoContainer = "#DBE2FF",
    onInfoContainer = "#001550",
    shadow = "rgb(26 28 32 / 0.08)",
)

internal val DarkPalette = SchedulerPalette(
    primary = "#AEC0FF",
    onPrimary = "#002C86",
    primaryContainer = "#1A3BC0",
    onPrimaryContainer = "#DBE2FF",
    secondary = "#9FD0C0",
    onSecondary = "#073529",
    secondaryContainer = "#1E4D40",
    onSecondaryContainer = "#CDE9DF",
    tertiary = "#E8B873",
    onTertiary = "#3F2A00",
    tertiaryContainer = "#5C3F12",
    onTertiaryContainer = "#F5E2C4",
    error = "#FFB3B0",
    onError = "#5F0010",
    errorContainer = "#8E0022",
    onErrorContainer = "#FFD9DA",
    background = "#121419",                 // near-black cool
    onBackground = "#E2E4E9",
    surface = "#15171C",
    onSurface = "#E2E4E9",
    surfaceVariant = "#3F444B",
    onSurfaceVariant = "#C2C7CE",
    surfaceContainerLowest = "#0E1014",
    surfaceContainerLow = "#181A20",
    surfaceContainer = "#1C1F25",
    surfaceContainerHigh = "#262A30",
    surfaceContainerHighest = "#31353C",
    outline = "#8A9099",
    outlineVariant = "#3F444B",
    inverseSurface = "#E2E4E9",
    inverseOnSurface = "#2A2D32",
    inversePrimary = "#2348E0",
    success = "#7FD8B4",
    onSuccess = "#00382A",
    successContainer = "#00513A",
    onSuccessContainer = "#CFF5E7",
    warning = "#FFB870",
    onWarning = "#492900",
    warningContainer = "#683D00",
    onWarningContainer = "#FFE0B8",
    info = "#AEC0FF",
    onInfo = "#002C86",
    infoContainer = "#1A3BC0",
    onInfoContainer = "#DBE2FF",
    shadow = "rgb(0 0 0 / 0.45)",
)

/**
 * Role name → value pairs, in the order the CSS custom properties are emitted.
 * Keeping this as one list means a new role is added in exactly one place.
 */
internal fun SchedulerPalette.asVariables(): List<Pair<String, String>> = listOf(
    "primary" to primary,
    "on-primary" to onPrimary,
    "primary-container" to primaryContainer,
    "on-primary-container" to onPrimaryContainer,
    "secondary" to secondary,
    "on-secondary" to onSecondary,
    "secondary-container" to secondaryContainer,
    "on-secondary-container" to onSecondaryContainer,
    "tertiary" to tertiary,
    "on-tertiary" to onTertiary,
    "tertiary-container" to tertiaryContainer,
    "on-tertiary-container" to onTertiaryContainer,
    "error" to error,
    "on-error" to onError,
    "error-container" to errorContainer,
    "on-error-container" to onErrorContainer,
    "background" to background,
    "on-background" to onBackground,
    "surface" to surface,
    "on-surface" to onSurface,
    "surface-variant" to surfaceVariant,
    "on-surface-variant" to onSurfaceVariant,
    "surface-container-lowest" to surfaceContainerLowest,
    "surface-container-low" to surfaceContainerLow,
    "surface-container" to surfaceContainer,
    "surface-container-high" to surfaceContainerHigh,
    "surface-container-highest" to surfaceContainerHighest,
    "outline" to outline,
    "outline-variant" to outlineVariant,
    "inverse-surface" to inverseSurface,
    "inverse-on-surface" to inverseOnSurface,
    "inverse-primary" to inversePrimary,
    "success" to success,
    "on-success" to onSuccess,
    "success-container" to successContainer,
    "on-success-container" to onSuccessContainer,
    "warning" to warning,
    "on-warning" to onWarning,
    "warning-container" to warningContainer,
    "on-warning-container" to onWarningContainer,
    "info" to info,
    "on-info" to onInfo,
    "info-container" to infoContainer,
    "on-info-container" to onInfoContainer,
    "shadow" to shadow,
)
